// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGorbwSYT9yXLDf_fr3FCjXy2lwQ6XKlc',
    appId: '1:694711600391:web:2b2df1fbdff0d3fbb6b1a2',
    messagingSenderId: '694711600391',
    projectId: 'retroquest-11331898-85115',
    authDomain: 'retroquest-11331898-85115.firebaseapp.com',
    storageBucket: 'retroquest-11331898-85115.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF63SPQsVDzs7IJLSGb2bI3NmKEcOKrcI',
    appId: '1:694711600391:android:3e288d8a349fb501b6b1a2',
    messagingSenderId: '694711600391',
    projectId: 'retroquest-11331898-85115',
    storageBucket: 'retroquest-11331898-85115.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0s0eDKEAR2GZAbsHW-cyqSxTdr624ZCI',
    appId: '1:694711600391:ios:762b1b02dd29e02bb6b1a2',
    messagingSenderId: '694711600391',
    projectId: 'retroquest-11331898-85115',
    storageBucket: 'retroquest-11331898-85115.firebasestorage.app',
    iosClientId: '694711600391-4f5rvnhqinhamu1ve2bda2tbst6p0a8d.apps.googleusercontent.com',
    iosBundleId: 'com.example.tempProject',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0s0eDKEAR2GZAbsHW-cyqSxTdr624ZCI',
    appId: '1:694711600391:ios:762b1b02dd29e02bb6b1a2',
    messagingSenderId: '694711600391',
    projectId: 'retroquest-11331898-85115',
    storageBucket: 'retroquest-11331898-85115.firebasestorage.app',
    iosClientId: '694711600391-4f5rvnhqinhamu1ve2bda2tbst6p0a8d.apps.googleusercontent.com',
    iosBundleId: 'com.example.tempProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGorbwSYT9yXLDf_fr3FCjXy2lwQ6XKlc',
    appId: '1:694711600391:web:425fd6553519709bb6b1a2',
    messagingSenderId: '694711600391',
    projectId: 'retroquest-11331898-85115',
    authDomain: 'retroquest-11331898-85115.firebaseapp.com',
    storageBucket: 'retroquest-11331898-85115.firebasestorage.app',
  );

}